# ==== File Paths ====
input_file: "src/DATA_Score/Scoring Code/Test_Article.json"
output_file: "src/DATA_Score/Scoring Code/gpt-5/Test_Article-gpt-5.jsonl"
exception_log_file: "src/DATA_Score/Scoring Code/gpt-5/Test_Article_exception_llm_output.log"

# ==== Vector DB ====
chroma_dir: "src/RAG_Databases/RAG_Data/chroma_db"
collection_name: "asean_scoring"

# ==== Models ====
embedding_model: "sentence-transformers/all-mpnet-base-v2"
filter_model: "nlpaueb/legal-bert-base-uncased"
openai_model: "gpt-5"
openai_api_url: "https://api.openai.com/v1/chat/completions"
openai_api_key: ""   # <<< fill in your key here >>>
proxy_url: null

# ==== Retrieval ====
top_k: 5
similarity_threshold: 1.0

# ==== Runtime ====
max_concurrent: 3
batch_size: 9
request_timeout: 300
cache_dir: "clause_cache_RAG"
